public interface Demo_of_method_overiding {
    
  void getColour();

}

/*public class ColourClassBase implements Demo_of_method_overiding{
 
    public void getColour(){
        system.debug('red');
    }
}

public class Green implements Demo_of_method_overiding{
 
    public  void getColour(){
        system.debug('Green');
    }
}

	
public class Orange implements Demo_of_method_overiding{
 
    public  void getColour(){
        system.debug('Orange');
    }
}
public class Objectdemo
{
	ColourClassBase ccb=new ColourClassBase();
	Green g=new Green();
	Orange o=new Orange();
	
}
*/
//interface example